import java.util.Arrays;
import java.util.List;
import java.util.function.ToIntFunction;

import static java.util.stream.Collectors.toList;

public class day5 {
    public static void main(String[] args) {
        // part1();
        // part2();
        part2fuckthis();
    }


    private static void part1() {
        var rows = List.of(DATA.split("\n"));

        var result = rows.stream()
                .mapToInt(getSeatID)
                .max();

        System.out.println(result.orElse(0));
    }

    private static void part2fuckthis() {
        int[] test = new int[1000];
        Arrays.setAll(test, i -> i + 54);
        var rows = List.of(DATA.split("\n"));

        var sorted = rows.stream()
                .mapToInt(getSeatID)
                .sorted()
                .toArray();

        System.out.println(Arrays.mismatch(test, sorted) + 54);
    }

    private static void part2() {
        var rows = List.of(DATA.split("\n"));

        var sorted = rows.stream()
                .mapToInt(getSeatID)
                .sorted()
                .toArray();

        var missingNumber = findMissingNumber(sorted);
        //System.out.println(missingNumber);
    }

    private static int findMissingNumber(int[] arr) {
        boolean searching = true;
        int factor = arr.length / 2;

        while (searching) {
            if (arr[factor] < factor + 54) {
                // missing number is in second half
                factor += factor / 2;
            }
            else {
                // missing number is in first half
                factor /= 2;
            }
        }

        return 4;
    }

    private static int findHoleInList(List<Integer> list, int startPos) {
        int[] noHoles = new int[list.size()];
        Arrays.setAll(noHoles, i -> i + 54);

        return 4;
    }

    private static final ToIntFunction<String> getSeatID = seatInput -> {
        String rowString = seatInput.substring(0, 7)
                .replace('F', '0')
                .replace('B', '1');
        String colString = seatInput.substring(7)
                .replace('L', '0')
                .replace('R', '1');

        int rowNumber = Integer.parseInt(rowString, 2);
        int colNumber = Integer.parseInt(colString, 2);

        return rowNumber * 8 + colNumber;
    };

    private static final String DATA = "FFBBBFBLRL\n" +
            "BFFFBFBRRR\n" +
            "BFFFBFBLRL\n" +
            "BFFBFBBLRR\n" +
            "BBFFBFFRLL\n" +
            "BFFFBFBRLR\n" +
            "FFFFBBBRLR\n" +
            "BBFFFBBRRR\n" +
            "BBFBFBBRRR\n" +
            "BFFBBBFLRR\n" +
            "FFBBFBBRLR\n" +
            "BBFFBFFLLL\n" +
            "BFFFBFBLLR\n" +
            "FBBFFBFLRR\n" +
            "FBBFBBFRRL\n" +
            "BFFBBBBRRR\n" +
            "BFBBBBFLLL\n" +
            "BFFBFBFLRR\n" +
            "FBBFFBFRRR\n" +
            "FFBFBFBLRL\n" +
            "BFFFFBFLRR\n" +
            "FBBFFFFLRR\n" +
            "BFFFBBBLLL\n" +
            "BFBFFFBRLL\n" +
            "FFBBBBBRLL\n" +
            "FFBBFFBLLR\n" +
            "FBFFBBFLRL\n" +
            "FFBFFBBRRL\n" +
            "BFBBBBFLLR\n" +
            "BFFFFBFRRL\n" +
            "BFFBFFFLLL\n" +
            "FBFFFBFLRL\n" +
            "FBBBFFFLLL\n" +
            "FFBFBBFRLR\n" +
            "FBBBFBFRRL\n" +
            "BFBBBFBLLL\n" +
            "FBFFFBFLRR\n" +
            "FBFBFFBLRR\n" +
            "BFFFFBFLRL\n" +
            "FBFBFFFRRL\n" +
            "FBBFBFBLRL\n" +
            "FBBFFBFLLL\n" +
            "FBFBBBBRRR\n" +
            "FBBBBBFLRR\n" +
            "FBBBFBBLLR\n" +
            "FFFBFBFRLL\n" +
            "FFFBBFFLRR\n" +
            "BFBBFFBRRL\n" +
            "FFBFBFBRRL\n" +
            "FBFBBBBLRR\n" +
            "BFFBBFFLLL\n" +
            "FFFBFBBRRL\n" +
            "BFBBFFFLRR\n" +
            "FBFBFBFLRL\n" +
            "BFBFFBFLLL\n" +
            "FBBBFBFRLR\n" +
            "FBBBFBFLLL\n" +
            "BFBFFFBLRR\n" +
            "BFFBFBFLRL\n" +
            "BFBBFFFRRR\n" +
            "FFFBFFFRLR\n" +
            "FFFBBBBRLL\n" +
            "FFBBBBBLLL\n" +
            "BFBBBFBRLL\n" +
            "FFFBBBFLLR\n" +
            "BBFFFFFRRL\n" +
            "FBFBBFFRLL\n" +
            "BFFBFBFRLR\n" +
            "FBFBBFFRRL\n" +
            "FBFBBFFLLL\n" +
            "FBFBBBBRLL\n" +
            "FBBFFBFLRL\n" +
            "BFFBFBBRRL\n" +
            "FBBFBFBRRL\n" +
            "FFFBBFBLRR\n" +
            "BFFBBBFRLL\n" +
            "FBFFFFFRRR\n" +
            "BFFFFBBLRR\n" +
            "FBBFFFBRRL\n" +
            "FBBBBBBRRR\n" +
            "FFFBBFFLLR\n" +
            "BBFBFFFRRL\n" +
            "BBFFFFBRRL\n" +
            "FBBBFBFLRL\n" +
            "FFBFBBFRRR\n" +
            "FFBBBFFLRL\n" +
            "BFFBFFFLRL\n" +
            "BFBFBFBRRR\n" +
            "BFBBFFBRLL\n" +
            "BFFFFBBLLR\n" +
            "FBBBFBBLRR\n" +
            "BFFBFFFLRR\n" +
            "BFFFBFBLLL\n" +
            "FBBBBBFRRR\n" +
            "BFFBFBFLLL\n" +
            "FBFFBFFRRL\n" +
            "BFBBFBBRRR\n" +
            "FBFFFBFRRL\n" +
            "BFBBBFBLLR\n" +
            "BFBBBBBRRR\n" +
            "FFFBFBFRRL\n" +
            "BFFFBFFLLL\n" +
            "BFFFFFFLRR\n" +
            "FFBBFFFRLL\n" +
            "BFFBFFFRRR\n" +
            "BBFFBBFLRL\n" +
            "FBFBBBBLLR\n" +
            "FFFBFFBLRL\n" +
            "FFBBBBBRLR\n" +
            "FBFFBFFRRR\n" +
            "BFBBFBBRLR\n" +
            "FBFBBBBLRL\n" +
            "BFBBFFFLLR\n" +
            "FBBBFBBLRL\n" +
            "BFFBBBFLLR\n" +
            "FFFBBBBRRR\n" +
            "BBFBFFFLRL\n" +
            "FBFBBFFLLR\n" +
            "BBFFFFBLRR\n" +
            "FFBBFFBRRR\n" +
            "FFBBBFBRLL\n" +
            "BFFFFBFLLL\n" +
            "BBFFBFBRLR\n" +
            "FBFBBFBRRL\n" +
            "FFFBBBFRRR\n" +
            "FBBBFBBRRL\n" +
            "FFFBFBBRRR\n" +
            "FBFFBBBRLL\n" +
            "FFBFBBBRLR\n" +
            "BFFFBBBRLL\n" +
            "FBBFBBBRLL\n" +
            "FBBBBBBLLR\n" +
            "FBFBBFBLRR\n" +
            "BFBFBFBLRL\n" +
            "FFFBFFBRLR\n" +
            "BFFFFFFRLL\n" +
            "BFFBFBBLRL\n" +
            "FBFFBFFLRR\n" +
            "FBFBBBBRLR\n" +
            "BBFFFBBLRL\n" +
            "FBBBFBBRRR\n" +
            "BBFBFBFRRR\n" +
            "FBFBFFFLRR\n" +
            "BBFBFFBLLL\n" +
            "FBBBFFFLLR\n" +
            "BFBFFBFRRL\n" +
            "BFBBBBFRLL\n" +
            "FFBFBFFLRL\n" +
            "FBBBBFBLRR\n" +
            "FBBBBFFLLR\n" +
            "FFBBFFBLLL\n" +
            "FBFFFBBRRR\n" +
            "FFBBBBFLLR\n" +
            "BFBFBFFRRL\n" +
            "FFBBBBBLRR\n" +
            "BFFFFFFRRL\n" +
            "BBFBFFFLRR\n" +
            "BFFBFBFRRL\n" +
            "BBFFBBBRRR\n" +
            "BBFFBFFLRL\n" +
            "FFFBFFBRRR\n" +
            "BFBFBBFRLR\n" +
            "BBFBFBBLRR\n" +
            "BFBBBBBRLL\n" +
            "FBBBFFBRRL\n" +
            "FBBBBBBRLL\n" +
            "FBBFBBFRLR\n" +
            "FBBFFFFRRL\n" +
            "BFBFFBFRRR\n" +
            "BFBBFFFLLL\n" +
            "FBFFBFFLLR\n" +
            "BFBBBFBLRR\n" +
            "BFFBBBBRLL\n" +
            "FBBBBBBLRR\n" +
            "FFBFFBFRRL\n" +
            "BBFFFBBRLL\n" +
            "FBFFFBBRLL\n" +
            "FFBBFFFLRL\n" +
            "BFBBBBFRRL\n" +
            "FFBFFBBRRR\n" +
            "BFFBBFBRLL\n" +
            "FFBFFFBLLR\n" +
            "FFBFFFFLLL\n" +
            "FBBBBBFLLR\n" +
            "FBFBFBBLLR\n" +
            "FBFBBFBRRR\n" +
            "BFBFFFFLRR\n" +
            "BFBBFFBRRR\n" +
            "FBFBFFFRRR\n" +
            "FFBFBBBRLL\n" +
            "BFBBBFBRRL\n" +
            "BFFBBBFLRL\n" +
            "BBFBFFFRLR\n" +
            "BBFBBFFLRR\n" +
            "FBBFFBBRRL\n" +
            "FBFBBBFLRL\n" +
            "FFBFBBFRRL\n" +
            "BFBFFBFLRL\n" +
            "BFFFBFFRLR\n" +
            "BBFBBFFRLR\n" +
            "FFBFBFBLLL\n" +
            "BFBFFBBRRR\n" +
            "BBFFBBBRRL\n" +
            "FBBBFBBLLL\n" +
            "FFFBFFFLRL\n" +
            "BBFFBFBLLL\n" +
            "BFBBFFFRLR\n" +
            "FBBBBFBLRL\n" +
            "BFBFBBBLRL\n" +
            "FFFBFBFRLR\n" +
            "FBFFFFBRRL\n" +
            "BFFBBFFLLR\n" +
            "FBFFFFFRRL\n" +
            "FBBFFBFRLR\n" +
            "FBBBFBBRLL\n" +
            "FBFFFFFLLR\n" +
            "BFBFBBBLLR\n" +
            "FFBBBBBRRR\n" +
            "BFFFBBFLLR\n" +
            "FBFBBFBLLL\n" +
            "FBBFFFFLLR\n" +
            "FBFFFFBLRL\n" +
            "FBBBFBBRLR\n" +
            "FBBFBBFLRR\n" +
            "FBBBBBBRRL\n" +
            "BBFBFBFLRL\n" +
            "FFBBBBFRRL\n" +
            "BFBBFBFLRL\n" +
            "BFFFFFFRRR\n" +
            "BBFBFBBLRL\n" +
            "BFBFFFFRLL\n" +
            "BBFFBFBRRR\n" +
            "BFBFFBBLLR\n" +
            "FBFBFFBRRL\n" +
            "FFBBFBFLLL\n" +
            "BFBFBBBRLR\n" +
            "FFBBFBFLRL\n" +
            "BBFFFFFRRR\n" +
            "FBFFFFFLRL\n" +
            "FFBFBFBRLL\n" +
            "BBFFFFFLRR\n" +
            "BBFFFBBRLR\n" +
            "FBFBBFBRLR\n" +
            "FBBBBBFLRL\n" +
            "FBBFFFBLRR\n" +
            "FFFBBFBLLL\n" +
            "BBFBFFBRLL\n" +
            "FFBFBFBLLR\n" +
            "BFBBFBBRRL\n" +
            "BFFBFFBLLL\n" +
            "BBFFBFFRLR\n" +
            "BBFFBBFLLR\n" +
            "BFFFFFBLRL\n" +
            "FBBFFFBLLL\n" +
            "FBFFFFBLLR\n" +
            "FBBFBFFRRL\n" +
            "BFBBBFFRRL\n" +
            "BBFFFBFLRL\n" +
            "FBFBFBFLLR\n" +
            "FBFFFBBRLR\n" +
            "BBFFBFBRLL\n" +
            "BBFFBFFRRL\n" +
            "BBFFBBFRLR\n" +
            "FBFFBFBRLL\n" +
            "BFBFBBFRRR\n" +
            "BFBBFBBLRL\n" +
            "FFBBFFBRLL\n" +
            "FBFFBFBRLR\n" +
            "BBFBFBBLLR\n" +
            "BFBBBFFRLL\n" +
            "FFBFFBFLLL\n" +
            "BFBFFBFRLR\n" +
            "BFFFBBFLRL\n" +
            "BFFFBBBLRL\n" +
            "BFBBBFFLLR\n" +
            "FBBFBBFRRR\n" +
            "BFFBFFBRRL\n" +
            "BFBFFBBRRL\n" +
            "BFBBFBFRLL\n" +
            "FBBFFBFRLL\n" +
            "FFBBBBFRLL\n" +
            "FBBBFFBRLL\n" +
            "BBFFBFBLRL\n" +
            "BBFFFFFLLL\n" +
            "BBFFFFBRRR\n" +
            "FBBBBFBRLR\n" +
            "BFFBFFBRRR\n" +
            "FFBFBFFRLL\n" +
            "FFFFBBFRRR\n" +
            "BBFBBFFLRL\n" +
            "FFFBBBFLRR\n" +
            "BFFBFBBLLL\n" +
            "BFBBFFFLRL\n" +
            "BFFBFFFRLL\n" +
            "BFBFFBBRLL\n" +
            "FFBBBBFLLL\n" +
            "BFFBFBBRRR\n" +
            "BFBBBBFRRR\n" +
            "FFBFFFFRLR\n" +
            "BFBFBFFRRR\n" +
            "BFBFBBBLRR\n" +
            "FBBBFFFLRR\n" +
            "FFBFFFBRRL\n" +
            "FBBFFFBRLR\n" +
            "FFFBFFBRLL\n" +
            "BFBBFFBLLR\n" +
            "FFBBFBBLRL\n" +
            "FFBFFFBRLR\n" +
            "BFBBFFFRLL\n" +
            "FBBFBBBLLL\n" +
            "FBBFFFFLLL\n" +
            "FFBFBBBRRR\n" +
            "FFFBBBFLRL\n" +
            "BBFFBBFLRR\n" +
            "FFFBFFFRLL\n" +
            "FFBBFBFRRR\n" +
            "FBFFBFBRRR\n" +
            "BFFBBFBLRL\n" +
            "FFFBBBFRLL\n" +
            "FBBBFFBRRR\n" +
            "FFBBBBFLRL\n" +
            "FFBFBBBRRL\n" +
            "FBFBFFBRRR\n" +
            "FBFFFBBLLL\n" +
            "FBBFFFFLRL\n" +
            "BFFFFBBRLR\n" +
            "BFBBBBBRLR\n" +
            "BBFFFBBRRL\n" +
            "BBFBFBFRLR\n" +
            "FBFFFFFLLL\n" +
            "FBFBBBBRRL\n" +
            "BFBFFFBLRL\n" +
            "FFFFBBBLLR\n" +
            "FFBBBFBRLR\n" +
            "FBBFFFFRRR\n" +
            "BBFBFFBLRL\n" +
            "BBFFFFBLRL\n" +
            "BFBFFBFLRR\n" +
            "FFFBBBBLRR\n" +
            "FBBBBBBLRL\n" +
            "FBBFFBFRRL\n" +
            "FBFFBBBRRL\n" +
            "FBFFBBFRRL\n" +
            "FFFBFBFLLR\n" +
            "BBFFFFFRLL\n" +
            "FFFBBBBLLR\n" +
            "BBFFBBBLRR\n" +
            "FBFBFFBLLR\n" +
            "BFBBFBBRLL\n" +
            "BFFFFFBRLR\n" +
            "FFFBFBBLRR\n" +
            "BFFBBBBLLL\n" +
            "BFFBBFBLLR\n" +
            "FBBBBBFRLR\n" +
            "BBFBFFBRLR\n" +
            "FBFFBFFLLL\n" +
            "FBBFBBBLLR\n" +
            "FFFFBBBRRL\n" +
            "FBBFBBFRLL\n" +
            "BFBFFFFRLR\n" +
            "FFFFBBBRLL\n" +
            "BFBBBFFLLL\n" +
            "BFBFBFFRLR\n" +
            "FBFBFFBRLL\n" +
            "FBBBFFFRLL\n" +
            "FBFBFFBRLR\n" +
            "FBBBBFFRLR\n" +
            "BBFBFFFRLL\n" +
            "BFFBBBBRLR\n" +
            "BFBFFFFRRL\n" +
            "FBBBFFFRRR\n" +
            "FFBFFBBRLR\n" +
            "FFBBBBFLRR\n" +
            "BBFBBFBRRL\n" +
            "BFFBFFBLLR\n" +
            "BBFBBFBRLL\n" +
            "FBFFBFBLLR\n" +
            "BBFBFBFLLR\n" +
            "FBFBFBBRLR\n" +
            "BBFBBFFRRL\n" +
            "BFBFFFBLLR\n" +
            "BFBFFBBLLL\n" +
            "FBFFBFBLRR\n" +
            "BFBBBBBLLL\n" +
            "BFFFBFFRRL\n" +
            "BFBBBFBRLR\n" +
            "BBFFFBFRLL\n" +
            "BFFBFFBRLL\n" +
            "BBFBBFFLLL\n" +
            "BFBBBBBLRR\n" +
            "FFFBFFBLLL\n" +
            "BBFFBBBRLL\n" +
            "FFFBBBBLRL\n" +
            "FFBBBFBLLR\n" +
            "FFBBFFBLRL\n" +
            "FFBBFFBLRR\n" +
            "FBBBBBBRLR\n" +
            "BFFFBBBLLR\n" +
            "FBBFBFBLRR\n" +
            "FBFBFBFRLR\n" +
            "FFBFBBBLRR\n" +
            "FFFFBBBLRL\n" +
            "FFFBBFFRLL\n" +
            "FFFBFFFLRR\n" +
            "BBFFFFBLLR\n" +
            "BFBFBFFLLL\n" +
            "FFBBBFFRLR\n" +
            "FBBFBFBRLL\n" +
            "FFBBBFBLLL\n" +
            "FBBFFFBLLR\n" +
            "BBFBFFBLRR\n" +
            "BFFFFBBLLL\n" +
            "FBBBFBFLLR\n" +
            "FFBBBFFLRR\n" +
            "BFFBBBFRRR\n" +
            "FFBFFFBLRR\n" +
            "FBBFFBBRLR\n" +
            "BFBBFBFLRR\n" +
            "FFFBBFFRRR\n" +
            "FFBFFFFRLL\n" +
            "FFFBFBFRRR\n" +
            "FFBFFFFRRR\n" +
            "FBBFBBBLRL\n" +
            "FFFBFBBRLR\n" +
            "FBBFFFBRLL\n" +
            "FFBFBFFRLR\n" +
            "FBBBBFFRRR\n" +
            "BFBFFBBLRR\n" +
            "FBFFBBBLRL\n" +
            "FBBFBBFLLR\n" +
            "BBFFFFFLRL\n" +
            "BFBBFBFRLR\n" +
            "BFFBFFBLRR\n" +
            "FFBFFFBRLL\n" +
            "FBFBFFBLLL\n" +
            "BFFFFFBLLL\n" +
            "FBFFBBFLLL\n" +
            "BFBFFBBRLR\n" +
            "FBFBBFBRLL\n" +
            "FFBBFBBRLL\n" +
            "BFFFBBBRLR\n" +
            "BFFFFFFLRL\n" +
            "BBFFFBBLLR\n" +
            "BFBFBBFLRL\n" +
            "FFBBBFFRRL\n" +
            "BBFFFBFLLL\n" +
            "BBFFBBBLLL\n" +
            "BBFFBFBLLR\n" +
            "FBFBBBFRLL\n" +
            "FFBBBBBRRL\n" +
            "FFBBBFFLLR\n" +
            "FFBFBBBLRL\n" +
            "BFFBFFBLRL\n" +
            "BFFFBFFRRR\n" +
            "BFBFFFBRRR\n" +
            "FFFBBBFRLR\n" +
            "FFBBFBBLLR\n" +
            "BFFFBBFLRR\n" +
            "FFBBBBFRRR\n" +
            "BFBFBBFLRR\n" +
            "FFFBBBBRRL\n" +
            "BFBFFBFRLL\n" +
            "FBFFBFFRLR\n" +
            "FBBFFFFRLR\n" +
            "BFBBBBBLRL\n" +
            "FFBBFBBLLL\n" +
            "FFBFBBFLLR\n" +
            "BFFBBBBLRL\n" +
            "BFBFFFFLRL\n" +
            "BBFFFBFRRL\n" +
            "FFBFFBBLRR\n" +
            "FBFBFBFRRR\n" +
            "BBFFFBFRLR\n" +
            "BFBBBFFLRR\n" +
            "BBFBFFBLLR\n" +
            "BBFBBFBLLR\n" +
            "FBFFFBFRLL\n" +
            "BFBFBBBLLL\n" +
            "FBBFBFFLRL\n" +
            "BFFFBBBLRR\n" +
            "BBFBFFBRRR\n" +
            "FBBFFFFRLL\n" +
            "BFFFBBBRRL\n" +
            "FBBFBBBRRR\n" +
            "FBBFFBFLLR\n" +
            "BFFFFFBRRL\n" +
            "FBFFFFBRLR\n" +
            "FBFBFBBRRR\n" +
            "FBFBFBFRLL\n" +
            "BFFBFFFRRL\n" +
            "FFFBBFFRRL\n" +
            "BFBFFFBRLR\n" +
            "FBBFBFFLRR\n" +
            "BFFFBFBRRL\n" +
            "FBFBBBFLLR\n" +
            "FBFBBBFRRR\n" +
            "FBFFBFBLRL\n" +
            "FFFFBBBRRR\n" +
            "FFBBBFFRRR\n" +
            "FFFBFBFLLL\n" +
            "BFBBFFBLRR\n" +
            "FBBFBFBRRR\n" +
            "BBFFBBFRRL\n" +
            "BBFFBFFRRR\n" +
            "BBFFBFFLRR\n" +
            "FBBFFBBLRR\n" +
            "BFBFFFFRRR\n" +
            "BFFBFBBRLR\n" +
            "BFFFBBFRLL\n" +
            "BFBFBBBRLL\n" +
            "BBFFFBBLRR\n" +
            "FFBBFBFLRR\n" +
            "FBFBBBFLLL\n" +
            "BBFFBBBLLR\n" +
            "FFBBFFFLRR\n" +
            "FBFFFBFRRR\n" +
            "BFBBFBBLLR\n" +
            "FFBBFBFRLR\n" +
            "BFBFFFFLLR\n" +
            "FBBBFBFRRR\n" +
            "BFBBFBFRRR\n" +
            "BFFBFBFRRR\n" +
            "FFBFBBBLLR\n" +
            "FBFBFFFRLR\n" +
            "FBBFBFBLLL\n" +
            "BFFBBFFRLL\n" +
            "FBBBBFBLLR\n" +
            "FFFBBBFLLL\n" +
            "BFBFBBFRLL\n" +
            "FFFBFBFLRR\n" +
            "FBBBBFBLLL\n" +
            "FFBBFBFRLL\n" +
            "BBFFBBFRRR\n" +
            "FFBFFBFRLL\n" +
            "FBFBFBBLLL\n" +
            "FBFFBBBLLR\n" +
            "FFFBFBBLRL\n" +
            "FFFBBFBRRR\n" +
            "FBFFBFFLRL\n" +
            "FBBFBFBLLR\n" +
            "BFBBBBFRLR\n" +
            "FBBFBFBRLR\n" +
            "FFFBFFBRRL\n" +
            "FBFBBFBLLR\n" +
            "BFFBFFFRLR\n" +
            "FFBFBFBLRR\n" +
            "BFBFBBBRRL\n" +
            "FBFFFFFLRR\n" +
            "FFFBBFFLLL\n" +
            "BFFFBBFRLR\n" +
            "FFBFFBFRLR\n" +
            "BBFFFFBRLR\n" +
            "BFFBFFBRLR\n" +
            "BFBFBFBRLR\n" +
            "FFBFFBBRLL\n" +
            "FBBBFFBLLL\n" +
            "BFBBBBBLLR\n" +
            "BFFFFBFRLL\n" +
            "FBBFFFBRRR\n" +
            "FFFFBBBLLL\n" +
            "FBFBFBBRRL\n" +
            "FBFFFFFRLR\n" +
            "FBFFBBFRRR\n" +
            "BFFBBFFLRL\n" +
            "BFBFBBBRRR\n" +
            "FBBFBFFRLR\n" +
            "BFFBBFBRRL\n" +
            "BFBBFBFRRL\n" +
            "FBFFFBBRRL\n" +
            "FBBFFBBLLL\n" +
            "FBFBFBBRLL\n" +
            "BFFFFBFRRR\n" +
            "FBBBFFBLLR\n" +
            "FBBFBBBLRR\n" +
            "FFBFBFFLLR\n" +
            "FBFFBFFRLL\n" +
            "FBBBFFBRLR\n" +
            "FBFFBBBLLL\n" +
            "FBFBFBFRRL\n" +
            "BBFBBFBLLL\n" +
            "FFBFBFFRRL\n" +
            "FBBBFFFRRL\n" +
            "FBFFBBFLRR\n" +
            "FBFBFFFLLR\n" +
            "BFFFFBBLRL\n" +
            "BFBFBFFLRL\n" +
            "FBFFFFBLLL\n" +
            "FBBBFFFLRL\n" +
            "BFFBBBBLLR\n" +
            "BFFBBBFLLL\n" +
            "BFFBBFBRRR\n" +
            "FBBBFBFRLL\n" +
            "BBFBFFFRRR\n" +
            "BFBBBFFRLR\n" +
            "FFBFBFBRRR\n" +
            "FBFFBBFRLL\n" +
            "FFFBBBBLLL\n" +
            "FBFFBFBRRL\n" +
            "BFFFFFBLLR\n" +
            "BFBFFFBLLL\n" +
            "FBFBBBBLLL\n" +
            "BFFBBFFRRL\n" +
            "BBFFBFBRRL\n" +
            "FBBFBFFRRR\n" +
            "BFBBFFBLLL\n" +
            "BFBFFBBLRL\n" +
            "BBFFFFFLLR\n" +
            "FFBFBBFRLL\n" +
            "FFBFFBFLLR\n" +
            "FBBFFBBLRL\n" +
            "BBFFFFBLLL\n" +
            "BFFFBFFLLR\n" +
            "FBFFFBFLLL\n" +
            "BBFBFBFLLL\n" +
            "FFBFFBBLRL\n" +
            "FBFFBBBRLR\n" +
            "BFFFFBBRRL\n" +
            "FFBBBBBLLR\n" +
            "FFBBFBFRRL\n" +
            "FFBFBBFLRL\n" +
            "FFBFBFFLRR\n" +
            "FFFBFFBLLR\n" +
            "BBFBFBBRLL\n" +
            "BFBBBBBRRL\n" +
            "FBFBBBFRLR\n" +
            "FBFBFFFRLL\n" +
            "BFFFFFFLLR\n" +
            "FBBBBFFLLL\n" +
            "FBBBFFBLRR\n" +
            "BFFFBFBLRR\n" +
            "FBBBFFFRLR\n" +
            "BFFFFFBRLL\n" +
            "FBBBBFBRRL\n" +
            "BFBBBFBLRL\n" +
            "FFBBFBBLRR\n" +
            "BFFBBFBLLL\n" +
            "BFBBFFFRRL\n" +
            "FBBBBFFRRL\n" +
            "BFFFBBFRRR\n" +
            "FFFBFFFRRR\n" +
            "FBFBBFBLRL\n" +
            "BFBBFFBLRL\n" +
            "BBFBBFBRLR\n" +
            "BBFBBFBLRL\n" +
            "FFBFBFFRRR\n" +
            "BBFFBBFLLL\n" +
            "FBBBFFBLRL\n" +
            "FBBFFBBRRR\n" +
            "BFFBFBFLLR\n" +
            "FBFBFBBLRR\n" +
            "BFFFBBBRRR\n" +
            "FBBFBFFLLL\n" +
            "FBFBBFFLRR\n" +
            "FFBBFFBRLR\n" +
            "FFBBBBBLRL\n" +
            "FFBBBFBRRL\n" +
            "BFBFBFBLRR\n" +
            "FBFFFFFRLL\n" +
            "BFBFBBFLLL\n" +
            "BBFBFBBRRL\n" +
            "FBFBFBFLLL\n" +
            "FFBFFBBLLR\n" +
            "FFFBFFFLLR\n" +
            "BFFFBFBRLL\n" +
            "FBBFFBBRLL\n" +
            "FBBFBFFLLR\n" +
            "BFFFFBFLLR\n" +
            "BFFFFFBLRR\n" +
            "BBFFFBFLRR\n" +
            "FBFBBFFRLR\n" +
            "BFBBFBFLLL\n" +
            "BFFBBBFRLR\n" +
            "BBFBFBBRLR\n" +
            "FFBBFBFLLR\n" +
            "BBFBFBFRRL\n" +
            "FBFBFBBLRL\n" +
            "FBFFFBBLRR\n" +
            "FBFBBFFRRR\n" +
            "BFFFFBFRLR\n" +
            "FBFFFBFLLR\n" +
            "FFBBBFFRLL\n" +
            "FBFBFFFLRL\n" +
            "BFFFBBFLLL\n" +
            "FFFBBFBRLL\n" +
            "FFBBBFFLLL\n" +
            "BFBBFBFLLR\n" +
            "FFBFBBFLLL\n" +
            "BFFBBBBRRL\n" +
            "BBFFBBBLRL\n" +
            "FBFFFFBLRR\n" +
            "BFBBFBBLRR\n" +
            "BFBBBFBRRR\n" +
            "BBFBFFFLLL\n" +
            "BFFBBFFRLR\n" +
            "BFFFBFFLRL\n" +
            "FBBBBFFRLL\n" +
            "FBFFBBFLLR\n" +
            "FBFBFFFLLL\n" +
            "BFFBBFFLRR\n" +
            "FFBBFBBRRL\n" +
            "BFBFBBFLLR\n" +
            "FFFBBFBLRL\n" +
            "FFBBFFFRRR\n" +
            "BBFFFBFRRR\n" +
            "FBBBBFFLRL\n" +
            "FFFBFBBLLL\n" +
            "FFFBBFFRLR\n" +
            "FBFFFBBLRL\n" +
            "BBFBFBFRLL\n" +
            "BBFFBBBRLR\n" +
            "FFFBBFBRLR\n" +
            "BBFBBFFRLL\n" +
            "BBFFFFFRLR\n" +
            "BFBFBFBLLL\n" +
            "BBFBFFFLLR\n" +
            "FBFFBFBLLL\n" +
            "BBFFFBBLLL\n" +
            "FBFFFFBRLL\n" +
            "BBFFFFBRLL\n" +
            "FFBFFFBRRR\n" +
            "BFFFFFFRLR\n" +
            "BBFFBBFRLL\n" +
            "BFBFFFBRRL\n" +
            "FFBBBBFRLR\n" +
            "FFBFFBFRRR\n" +
            "BBFBFBFLRR\n" +
            "FFBFFBFLRL\n" +
            "BFBFBFFLLR\n" +
            "FBBBBBFLLL\n" +
            "FFBFFFBLLL\n" +
            "FFBBBFBLRR\n" +
            "FFFFBBFRRL\n" +
            "FBFBBBFLRR\n" +
            "BFFBBFFRRR\n" +
            "FBFBBBFRRL\n" +
            "BFFFFFBRRR\n" +
            "BFBFBBFRRL\n" +
            "BFBFBFBRLL\n" +
            "BFBFFFFLLL\n" +
            "FBBBBBFRRL\n" +
            "BFBBBBFLRR\n" +
            "BBFBBFFRRR\n" +
            "BFFBFFFLLR\n" +
            "BFBBFBBLLL\n" +
            "FBFFFFBRRR\n" +
            "FBFFFBFRLR\n" +
            "BFFBFBBRLL\n" +
            "FFBBBFBRRR\n" +
            "FFBBFFFLLR\n" +
            "BBFBBFFLLR\n" +
            "BFBBFFBRLR\n" +
            "FFFBBFFLRL\n" +
            "BFFFFFFLLL\n" +
            "FFBBFFFRLR\n" +
            "BFFBFBFRLL\n" +
            "FFBFFBBLLL\n" +
            "BFFFBFFLRR\n" +
            "FFBFFFFLRR\n" +
            "FBBBBFBRLL\n" +
            "BFBFFBFLLR\n" +
            "FFBBFFBRRL\n" +
            "BFFBBFBLRR\n" +
            "FFBFFBFLRR\n" +
            "BFFBFBBLLR\n" +
            "FBBFBBFLLL\n" +
            "FBFFBBBLRR\n" +
            "BBFFBFFLLR\n" +
            "BFBBBFFRRR\n" +
            "FFFBFFFRRL\n" +
            "FBBFBBBRRL\n" +
            "FFFBFBBLLR\n" +
            "BFFFBFFRLL\n" +
            "BBFBFFBRRL\n" +
            "FFBFFFFRRL\n" +
            "FFBFBFBRLR\n" +
            "FBBFBFFRLL\n" +
            "FFFBBFBLLR\n" +
            "FFFBBBFRRL\n" +
            "FBBBBBFRLL\n" +
            "BFFFBBFRRL\n" +
            "BFBFBFBRRL\n" +
            "FBBBBFFLRR\n" +
            "FFFBBFBRRL\n" +
            "BFFBBFBRLR\n" +
            "BBFBFBBLLL\n" +
            "FFBFFFFLLR\n" +
            "FFBFFFFLRL\n" +
            "FFFFBBBLRR\n" +
            "BBFBBFBLRR\n" +
            "FBBBFBFLRR\n" +
            "FFFBFBBRLL\n" +
            "FBFFBBFRLR\n" +
            "FFBFBBFLRR\n" +
            "FFFBFBFLRL\n" +
            "FFFBBBBRLR\n" +
            "FBBFBBBRLR\n" +
            "FBFBFFBLRL\n" +
            "BFBBBBFLRL\n" +
            "BFFFFBBRRR\n" +
            "BFFBBBFRRL\n" +
            "BFFFFBBRLL\n" +
            "BFBFBFFLRR\n" +
            "BBFFBFBLRR\n" +
            "FBBFBBFLRL\n" +
            "FFFBFFFLLL\n" +
            "FBBBBFBRRR\n" +
            "FBFFFBBLLR\n" +
            "FBBFFBBLLR\n" +
            "FFBBFFFLLL\n" +
            "FFBFBFFLLL\n" +
            "FBFBFBFLRR\n" +
            "BBFFFBFLLR\n" +
            "BFFBBBBLRR\n" +
            "FBBFFFBLRL\n" +
            "FFFBFFBLRR\n" +
            "BFBFBFBLLR\n" +
            "FBFBBFFLRL\n" +
            "BFBFBFFRLL\n" +
            "FFBFBBBLLL\n" +
            "FBFFBBBRRR\n" +
            "FFBBFFFRRL\n" +
            "FFBBFBBRRR\n" +
            "FFBFFFBLRL\n" +
            "BFBBBFFLRL";
}
