import java.util.Arrays;
import java.util.function.*;

public class day6 {

    public static void main(String[] args) {
        part1();
        part2();
    }

    private static void part1() {
        var groupAnswers = DATA.split("\n\n");

        var combinedAnswers = Arrays.stream(groupAnswers)
                .map(s -> s.replace("\n", ""))
                .mapToInt(answerToBitPattern)
                .map(Integer::bitCount)
                .sum();

        System.out.println(combinedAnswers);
    }

    private static void part2() {
        var groupAnswers = DATA.split("\n\n");

        var combinedAnswers = Arrays.stream(groupAnswers)
                .mapToInt(countGroupCommonAnswers)
                .sum();

        System.out.println(combinedAnswers);
    }

    private static final IntBinaryOperator bitMaskOr = (int acc, int cur) -> {
        return acc | 1 << (cur - 97);
    };

    private static final IntBinaryOperator bitMaskAnd = (int acc, int cur) -> {
        return acc & cur;
    };

    private static final ToIntFunction<String> answerToBitPattern = answerString -> {
        return answerString.chars().reduce(0, bitMaskOr);
    };

    private static final ToIntFunction<String> countGroupCommonAnswers = groupAnswers -> {
        var commonAnswers = groupAnswers.lines()
                .mapToInt(answerToBitPattern)
                .reduce(Integer.MAX_VALUE, bitMaskAnd);

        return Integer.bitCount(commonAnswers);
    };

    private static final String DATA = "f\n" +
            "v\n" +
            "ki\n" +
            "\n" +
            "krlugwajesizdptcvqh\n" +
            "vwuzeicrdhpastknmo\n" +
            "zchstrwvaxkipeoud\n" +
            "hvwzoetbdisrakxcpu\n" +
            "\n" +
            "amc\n" +
            "acm\n" +
            "cam\n" +
            "\n" +
            "ldtzbxkgp\n" +
            "zpbkadlqxy\n" +
            "xyzdplkb\n" +
            "\n" +
            "wopvsltibzh\n" +
            "vuirlfoqzhe\n" +
            "hzilqovmg\n" +
            "\n" +
            "hilxpyvmugzbjotqsnda\n" +
            "vulgophjzidqtyasmn\n" +
            "voilzgnqmejswydaturph\n" +
            "\n" +
            "x\n" +
            "x\n" +
            "x\n" +
            "\n" +
            "xuhtlimyoksvqbjwz\n" +
            "xtjzibvksuwlyhoqm\n" +
            "vxuzsojybmhiltwkdq\n" +
            "qwtozjmbuvyiklshx\n" +
            "kxryhiwuvtmalbozqsj\n" +
            "\n" +
            "iutvxp\n" +
            "ouix\n" +
            "ixuv\n" +
            "kipbxu\n" +
            "\n" +
            "aqogtkx\n" +
            "otqgyivamb\n" +
            "ouygqaet\n" +
            "qgnjhrosdpac\n" +
            "vgqomtbfwa\n" +
            "\n" +
            "bfomjtvacns\n" +
            "smjtnabfvop\n" +
            "mjsneafotbv\n" +
            "vsntjmobfa\n" +
            "\n" +
            "lo\n" +
            "ol\n" +
            "ol\n" +
            "lo\n" +
            "ol\n" +
            "\n" +
            "nqfkygu\n" +
            "gykuqf\n" +
            "\n" +
            "zc\n" +
            "bcyg\n" +
            "c\n" +
            "itc\n" +
            "\n" +
            "dcwmainsjvqkrgtbpl\n" +
            "dgmawcrnklsiqvpjbt\n" +
            "kngcwbidvjmplrtsaq\n" +
            "rbpvswldcanjkqitgm\n" +
            "vtglipnqsmjrbakdwc\n" +
            "\n" +
            "nflmv\n" +
            "owixltsyqkr\n" +
            "clzphbj\n" +
            "lzn\n" +
            "ladeuhgj\n" +
            "\n" +
            "qztporeaj\n" +
            "qeorlbghuavx\n" +
            "\n" +
            "oarwuskqcvyxdjzfig\n" +
            "fqrhuzvjisgwlcykoda\n" +
            "pfuqytkdagoimjrwvscz\n" +
            "uvekgjaqsfrzcdowniy\n" +
            "\n" +
            "iczbrqafnotspjluex\n" +
            "prqblfagxuhzejw\n" +
            "\n" +
            "qbkdsg\n" +
            "dsgkbmq\n" +
            "dgsbqrkz\n" +
            "nsgkbwixpfqd\n" +
            "sgqkbcd\n" +
            "\n" +
            "ahgjmxbkornzqvfe\n" +
            "bjpxziqfoymldhrncweta\n" +
            "\n" +
            "eafmcto\n" +
            "qtbramfkio\n" +
            "mtgofas\n" +
            "\n" +
            "gihwmotrbkc\n" +
            "ckrhbmoigwt\n" +
            "khofbirmwtcg\n" +
            "whkcbgmoitr\n" +
            "mwtogbhckir\n" +
            "\n" +
            "lzqpsr\n" +
            "espqi\n" +
            "\n" +
            "wnckgyjbt\n" +
            "tcromuywblj\n" +
            "dqawybsjt\n" +
            "\n" +
            "kgtoc\n" +
            "gc\n" +
            "fmcuzpalgqvrd\n" +
            "gcj\n" +
            "\n" +
            "hibxpevkgr\n" +
            "atekbvrpwx\n" +
            "zeoxkbpvr\n" +
            "xvkbepraz\n" +
            "\n" +
            "elugojtykhd\n" +
            "fzrdkvhye\n" +
            "dkjiybeh\n" +
            "\n" +
            "iyxbgatjveqopls\n" +
            "ilpstboqjvygxae\n" +
            "bptrzxygeaviojslq\n" +
            "bejliptxagvysqo\n" +
            "\n" +
            "idvfoykrmc\n" +
            "qsbxjemtaulkfwpizgndh\n" +
            "\n" +
            "qkegfzuljyniv\n" +
            "rpydfujqlkgivzen\n" +
            "glkzejqviuyfn\n" +
            "vyukqbneliogfjz\n" +
            "efgikqajuynclmvz\n" +
            "\n" +
            "vrk\n" +
            "kor\n" +
            "\n" +
            "twhlks\n" +
            "kth\n" +
            "kthe\n" +
            "thkq\n" +
            "htxk\n" +
            "\n" +
            "zdveobcgplk\n" +
            "vzebkpdlcog\n" +
            "kbpdleovczg\n" +
            "viokeglfdzcpby\n" +
            "ocvlegpbdkz\n" +
            "\n" +
            "n\n" +
            "n\n" +
            "n\n" +
            "n\n" +
            "n\n" +
            "\n" +
            "nwaq\n" +
            "wa\n" +
            "wa\n" +
            "wa\n" +
            "wa\n" +
            "\n" +
            "xkyhuetdjrbnqcgwspfl\n" +
            "wtpnucdhexjgkryfslq\n" +
            "egryjopufdwcshntqxkl\n" +
            "kugdyljhesxwrctpnqf\n" +
            "\n" +
            "mich\n" +
            "iahecm\n" +
            "inhmuck\n" +
            "\n" +
            "kgd\n" +
            "xdqbwyh\n" +
            "gmsd\n" +
            "\n" +
            "c\n" +
            "vcd\n" +
            "ic\n" +
            "\n" +
            "s\n" +
            "e\n" +
            "s\n" +
            "\n" +
            "yekfdgcnts\n" +
            "orimxgh\n" +
            "\n" +
            "ungma\n" +
            "ongmht\n" +
            "ndmg\n" +
            "\n" +
            "paticu\n" +
            "etcrxmnu\n" +
            "wckyjdug\n" +
            "\n" +
            "xz\n" +
            "tmzx\n" +
            "xzdofn\n" +
            "zbx\n" +
            "znbx\n" +
            "\n" +
            "zhsp\n" +
            "retfi\n" +
            "skdjyphbr\n" +
            "omvgwqcxl\n" +
            "\n" +
            "mojsgnelawucyifx\n" +
            "noycpzrmfweqgujvxlsia\n" +
            "alechfxjnomiugswy\n" +
            "\n" +
            "nqvabm\n" +
            "vsx\n" +
            "vksdp\n" +
            "\n" +
            "mk\n" +
            "mk\n" +
            "mk\n" +
            "km\n" +
            "\n" +
            "bnqogpwchxjvmkeuzr\n" +
            "nkzwhuomqbcpagxe\n" +
            "nbgmozupwcekqxh\n" +
            "zbgewmpqxckohun\n" +
            "kzucnqowxmghebp\n" +
            "\n" +
            "gwtxncpidsqjkamo\n" +
            "wjegiuscmnokdqtp\n" +
            "tewnigmrocdqjuspk\n" +
            "\n" +
            "niebjdu\n" +
            "luehqscpt\n" +
            "\n" +
            "risdekvawtmofyjnhgzcbxp\n" +
            "yxqeavobjzstwnhrpugmcik\n" +
            "\n" +
            "arlihzewukqpgftb\n" +
            "gtolifhaeszqrkdp\n" +
            "bteqlkgufzhirap\n" +
            "ieagztjqflnrkmchvpx\n" +
            "ypfqhdikgbztaerl\n" +
            "\n" +
            "azsnduvwtxofqc\n" +
            "qtxwocmvp\n" +
            "eoxtgcbwvq\n" +
            "olcxwvqtk\n" +
            "\n" +
            "ydpzkxialhwub\n" +
            "xviclpyhbdmwutz\n" +
            "rqepsbxwunoyghfijdlz\n" +
            "\n" +
            "kwyztdvfahgl\n" +
            "mtakcpujrgq\n" +
            "\n" +
            "lqcmey\n" +
            "ch\n" +
            "ic\n" +
            "cth\n" +
            "\n" +
            "fhbcm\n" +
            "bhf\n" +
            "hmfb\n" +
            "kpfxrebdh\n" +
            "fbh\n" +
            "\n" +
            "aehnmjrbvwscfzk\n" +
            "ehvjczwmnasbfk\n" +
            "mhjzinscwbkefav\n" +
            "\n" +
            "ankegwhcj\n" +
            "wuodpgsmibz\n" +
            "wgye\n" +
            "gfqwtr\n" +
            "\n" +
            "nmxetkjyawv\n" +
            "bsuvgiocrhlpdfazq\n" +
            "\n" +
            "bupyxki\n" +
            "aixokljupb\n" +
            "ouxpkibzr\n" +
            "kxuypjbi\n" +
            "fqwnvukxithpb\n" +
            "\n" +
            "bscvpfmhnti\n" +
            "aqjvxyzew\n" +
            "\n" +
            "ghlpyjaz\n" +
            "pjnhz\n" +
            "npzjdh\n" +
            "\n" +
            "yslmtadvrgp\n" +
            "agnlurt\n" +
            "\n" +
            "yeclmqgnkp\n" +
            "zrinodcwths\n" +
            "lbgvnucp\n" +
            "bynapc\n" +
            "ncfj\n" +
            "\n" +
            "bkyzqocdl\n" +
            "yldhqazrbkc\n" +
            "yzblpcdkq\n" +
            "dylqbzkcp\n" +
            "\n" +
            "lxkhdtneyguj\n" +
            "kytqujghnxeds\n" +
            "cjyxhtouekdwpgmn\n" +
            "gtdbjxkznhuyel\n" +
            "dugqnajkeythx\n" +
            "\n" +
            "jonkltyb\n" +
            "xnkltcybeo\n" +
            "ylokbtn\n" +
            "ontkbly\n" +
            "nojmykltb\n" +
            "\n" +
            "juqkxvprfonhmasb\n" +
            "vkzrgdatcjlpxniub\n" +
            "bkprcvuxygnaj\n" +
            "\n" +
            "p\n" +
            "z\n" +
            "r\n" +
            "z\n" +
            "z\n" +
            "\n" +
            "pxqryf\n" +
            "tck\n" +
            "\n" +
            "rjvlmudx\n" +
            "unsmxrzja\n" +
            "mruxjlt\n" +
            "\n" +
            "yhrcbnuvdpt\n" +
            "ufhdrypvjn\n" +
            "gpdrvhnuyq\n" +
            "pnydrjvuh\n" +
            "yunhpdrv\n" +
            "\n" +
            "pmohzjnbwrl\n" +
            "czeoyplmrbhwij\n" +
            "lgwbqjdsmfzvpart\n" +
            "zlwjnprbmk\n" +
            "\n" +
            "tkljwpiho\n" +
            "ihjkfotlp\n" +
            "\n" +
            "am\n" +
            "xahm\n" +
            "am\n" +
            "jma\n" +
            "\n" +
            "kuwdhv\n" +
            "ykvhuwdmr\n" +
            "\n" +
            "myhpqsvatfg\n" +
            "fyjtavmshpqg\n" +
            "\n" +
            "fl\n" +
            "fl\n" +
            "\n" +
            "tq\n" +
            "tq\n" +
            "uqc\n" +
            "kqw\n" +
            "kqw\n" +
            "\n" +
            "x\n" +
            "dx\n" +
            "x\n" +
            "ml\n" +
            "\n" +
            "jhcmxinpuezodalvbg\n" +
            "jmnyazhdvelioptsg\n" +
            "\n" +
            "tzncvyqjibaf\n" +
            "zjvaqfnicytb\n" +
            "\n" +
            "jadmbkr\n" +
            "dmrtlsih\n" +
            "drgnjxm\n" +
            "dmfrk\n" +
            "\n" +
            "gfuaivl\n" +
            "erycvaso\n" +
            "wtpbxqzkmnhjd\n" +
            "\n" +
            "e\n" +
            "e\n" +
            "e\n" +
            "\n" +
            "pfawmqlvrj\n" +
            "hfv\n" +
            "fv\n" +
            "ohvf\n" +
            "\n" +
            "xpygkrsnflzc\n" +
            "vkrcpgxlbzynsmwif\n" +
            "escpkxfazlrnyg\n" +
            "nyrsfgpltkzcx\n" +
            "fsrnpxlcykzg\n" +
            "\n" +
            "cselqzvrfijuyw\n" +
            "yxcofwzku\n" +
            "zfydhcnuwp\n" +
            "\n" +
            "lj\n" +
            "lj\n" +
            "lj\n" +
            "\n" +
            "lrwskbqi\n" +
            "\n" +
            "zbh\n" +
            "bzch\n" +
            "zbh\n" +
            "\n" +
            "bfzdkepcjylq\n" +
            "cdepzqlybjfk\n" +
            "\n" +
            "pr\n" +
            "c\n" +
            "q\n" +
            "e\n" +
            "\n" +
            "ryjlfns\n" +
            "yrqlsn\n" +
            "nrlsy\n" +
            "\n" +
            "tuwlz\n" +
            "tlwzu\n" +
            "ultwzm\n" +
            "luzwt\n" +
            "wuzltpx\n" +
            "\n" +
            "maflwvsozx\n" +
            "qwmxeuofrvc\n" +
            "\n" +
            "vlktpweyrbf\n" +
            "bzrelyhtwv\n" +
            "meljvwnyo\n" +
            "gqwcyldve\n" +
            "\n" +
            "cgypxd\n" +
            "gtxfpcd\n" +
            "jxaph\n" +
            "xgtpkuf\n" +
            "\n" +
            "twalnicrg\n" +
            "igtwrnlac\n" +
            "\n" +
            "l\n" +
            "sl\n" +
            "ml\n" +
            "l\n" +
            "ml\n" +
            "\n" +
            "lu\n" +
            "lqxd\n" +
            "ljmvn\n" +
            "lc\n" +
            "ldxt\n" +
            "\n" +
            "dkjw\n" +
            "zwg\n" +
            "ihgw\n" +
            "owhg\n" +
            "\n" +
            "mc\n" +
            "fwc\n" +
            "sc\n" +
            "\n" +
            "skoap\n" +
            "gqmskncfto\n" +
            "\n" +
            "wpmikqjz\n" +
            "zmwkjpiq\n" +
            "tqmjwpkiz\n" +
            "pwjmzisgkq\n" +
            "brjkqzimdpcf\n" +
            "\n" +
            "wa\n" +
            "vxtja\n" +
            "at\n" +
            "\n" +
            "xjlvaun\n" +
            "ajuvq\n" +
            "uohkjyeq\n" +
            "sprcu\n" +
            "\n" +
            "jomzpauflsyndwkiqehgrxb\n" +
            "buwpsrehidgkjaymfzlonx\n" +
            "nfairoxhbvkszwepdjugmy\n" +
            "xhdnbkfrutjozaygwseipm\n" +
            "\n" +
            "skqrhtiu\n" +
            "axutrdyg\n" +
            "zunxgrdt\n" +
            "rtulx\n" +
            "vtuglrx\n" +
            "\n" +
            "fltwbmay\n" +
            "mtbflya\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "as\n" +
            "\n" +
            "i\n" +
            "ni\n" +
            "i\n" +
            "i\n" +
            "\n" +
            "kobslnqvd\n" +
            "ofqbpvkdig\n" +
            "vbolqdrjk\n" +
            "\n" +
            "ctbinzxjlrmweyaqgupks\n" +
            "bvaxeuiqsyznwrjlgtmcpk\n" +
            "blcqinmegxsrzpwtukoajy\n" +
            "\n" +
            "mqeuarkotb\n" +
            "mruxotsewk\n" +
            "kmrwegiobut\n" +
            "kneumcjdlvort\n" +
            "\n" +
            "qf\n" +
            "fq\n" +
            "fq\n" +
            "\n" +
            "radclnjixto\n" +
            "tuigaldzrxo\n" +
            "tvabplfheoyrix\n" +
            "lxoarijktw\n" +
            "\n" +
            "vyhaco\n" +
            "aycovh\n" +
            "oyvhac\n" +
            "vcaohy\n" +
            "\n" +
            "af\n" +
            "af\n" +
            "af\n" +
            "af\n" +
            "\n" +
            "nrocs\n" +
            "rdypjefcx\n" +
            "frajcd\n" +
            "\n" +
            "ezgjnudoblch\n" +
            "rgtnuedjlzvc\n" +
            "nlidzswmjcfekagxu\n" +
            "lnjduzqyceg\n" +
            "gebdluzjnrc\n" +
            "\n" +
            "ohstpqcmjewk\n" +
            "eodshjutmn\n" +
            "\n" +
            "jobvc\n" +
            "cifonekz\n" +
            "\n" +
            "fc\n" +
            "fc\n" +
            "mkc\n" +
            "\n" +
            "xep\n" +
            "ge\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "p\n" +
            "\n" +
            "jnuzmkv\n" +
            "bnum\n" +
            "ajnsmu\n" +
            "knmuq\n" +
            "nimuywp\n" +
            "\n" +
            "djfl\n" +
            "lfdj\n" +
            "dlfj\n" +
            "ldfj\n" +
            "\n" +
            "qxdefoawjbcltz\n" +
            "jqlebatdnfowxzc\n" +
            "yizactgspvqeduljrmkbhof\n" +
            "\n" +
            "p\n" +
            "u\n" +
            "\n" +
            "hg\n" +
            "bghdkupm\n" +
            "gh\n" +
            "gh\n" +
            "gvfh\n" +
            "\n" +
            "tczbmignve\n" +
            "gtzncvmebi\n" +
            "zmcvteingb\n" +
            "nizbmgcvet\n" +
            "\n" +
            "mpl\n" +
            "mlp\n" +
            "lpm\n" +
            "ldmjp\n" +
            "epml\n" +
            "\n" +
            "slmfr\n" +
            "urlm\n" +
            "lmr\n" +
            "rlqegimjk\n" +
            "plmtr\n" +
            "\n" +
            "avdysumewt\n" +
            "tyvwemsdau\n" +
            "yuwmsetdva\n" +
            "\n" +
            "eokxsimwqbjfzrtygpadl\n" +
            "dimgsbprohwzlfjet\n" +
            "tqrvibsawfpojlmdezg\n" +
            "\n" +
            "nlbwtev\n" +
            "syvbntd\n" +
            "tbmvn\n" +
            "\n" +
            "fgthm\n" +
            "thfgm\n" +
            "gfhtm\n" +
            "thmfgxz\n" +
            "tghmf\n" +
            "\n" +
            "gcdal\n" +
            "lgvachdu\n" +
            "lbcagvdx\n" +
            "ycgdljswmqa\n" +
            "olragcd\n" +
            "\n" +
            "fmghvbcl\n" +
            "hmpfovcbsyi\n" +
            "djlfcsmbhi\n" +
            "nrbuefmkcqahtwz\n" +
            "\n" +
            "plbgwxzndeufjo\n" +
            "lhwdoxgufejbnpz\n" +
            "ufoxwlngebjpdvz\n" +
            "uezonlbfjgxwdp\n" +
            "kldzgfoenubwpjx\n" +
            "\n" +
            "ebqpacdxm\n" +
            "lobyxurpe\n" +
            "\n" +
            "iafnzmpdhsbvq\n" +
            "dhisamvqbzgnf\n" +
            "suivfzdbhoqanmpl\n" +
            "dszqbilhomanvf\n" +
            "qbmdsxiczvfjnha\n" +
            "\n" +
            "bmxtzvunojdwy\n" +
            "wbvxjyztumo\n" +
            "jvmywoutzbx\n" +
            "tvzoxmygbwju\n" +
            "guobtymjzwvx\n" +
            "\n" +
            "obfdeual\n" +
            "obedalcf\n" +
            "fldoeba\n" +
            "elkdbafog\n" +
            "\n" +
            "huziqdycmaknstrbjwp\n" +
            "zpiuqnhcskarjvbydewt\n" +
            "kpczadnqwtrjiyvusbh\n" +
            "cytzsidqjwapbnkurh\n" +
            "qglkibzhxfajpdswuycnrt\n" +
            "\n" +
            "ch\n" +
            "hx\n" +
            "hr\n" +
            "xh\n" +
            "h\n" +
            "\n" +
            "vpxdhecsz\n" +
            "efvodzc\n" +
            "mvbzwedq\n" +
            "vrexozd\n" +
            "\n" +
            "sonyemfcila\n" +
            "yckafemou\n" +
            "\n" +
            "gyuvq\n" +
            "uqyzgdv\n" +
            "\n" +
            "w\n" +
            "k\n" +
            "x\n" +
            "w\n" +
            "\n" +
            "ptmuaewfqo\n" +
            "ivfpeqaso\n" +
            "taqrsepfo\n" +
            "qydxplfgnoae\n" +
            "\n" +
            "vd\n" +
            "vd\n" +
            "vd\n" +
            "dv\n" +
            "\n" +
            "mrly\n" +
            "lyurm\n" +
            "mxorly\n" +
            "elymjr\n" +
            "\n" +
            "nkzdrgvw\n" +
            "dwzvgknr\n" +
            "nzkvwdr\n" +
            "znrkvwuld\n" +
            "\n" +
            "bjgsupezhrfkciqlax\n" +
            "brjgckvlfsxaeuqpiz\n" +
            "srbxfzgpjkuqlcaie\n" +
            "ueapzixfbsclkrqjvg\n" +
            "dofbyxrlagipqsecujzk\n" +
            "\n" +
            "sc\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "\n" +
            "faeyhclsdnq\n" +
            "achyqsnelf\n" +
            "lfqmsycnahe\n" +
            "qnhaselfcdy\n" +
            "\n" +
            "hwtbmuriagejspdc\n" +
            "chewjispudtrgmab\n" +
            "egcrhipautjsdmb\n" +
            "fczsirmkejxdgltuabvqhp\n" +
            "ntohrasmjicupbegd\n" +
            "\n" +
            "ofuzxdvbw\n" +
            "rmptsjlnzba\n" +
            "zeb\n" +
            "ebziy\n" +
            "\n" +
            "resicqjluzn\n" +
            "wgdyalncs\n" +
            "\n" +
            "usbhypxw\n" +
            "wumhpxsby\n" +
            "hpwysxbu\n" +
            "\n" +
            "djrzg\n" +
            "bvysdwhgz\n" +
            "\n" +
            "xfjzgylensdcpt\n" +
            "rytgpxzjnfsdlc\n" +
            "\n" +
            "pqwn\n" +
            "npqw\n" +
            "pqnw\n" +
            "qpnw\n" +
            "\n" +
            "pe\n" +
            "zpweb\n" +
            "\n" +
            "zp\n" +
            "zpo\n" +
            "pz\n" +
            "pz\n" +
            "\n" +
            "pctyum\n" +
            "ptuhmyc\n" +
            "pdymtzfruc\n" +
            "puyctm\n" +
            "tupcymas\n" +
            "\n" +
            "ordjynitsvcuzel\n" +
            "tlrnuqd\n" +
            "ldrxbtnfu\n" +
            "luwrtnkd\n" +
            "tndfhlrub\n" +
            "\n" +
            "kduwpcyejqzf\n" +
            "jtchayqweizxsupkbm\n" +
            "pweuvyzqjrkoc\n" +
            "\n" +
            "oxkmpbgwszny\n" +
            "oghymwnkpsbzux\n" +
            "bpoxngwyszmk\n" +
            "\n" +
            "lgs\n" +
            "hg\n" +
            "gb\n" +
            "\n" +
            "dleamc\n" +
            "ctlheyk\n" +
            "ixzjngwufco\n" +
            "rdcvaste\n" +
            "\n" +
            "eoxkgs\n" +
            "segkx\n" +
            "akvugsxe\n" +
            "xsgek\n" +
            "kxzseg\n" +
            "\n" +
            "ftinexgmraqojwszcyuhblv\n" +
            "lzpjktvxdgcbhqawmefysoinr\n" +
            "\n" +
            "jn\n" +
            "ojvy\n" +
            "e\n" +
            "hksfzgtibaxc\n" +
            "jduq\n" +
            "\n" +
            "bqgfvmzp\n" +
            "mxvg\n" +
            "ekvmgh\n" +
            "vtamg\n" +
            "matgv\n" +
            "\n" +
            "e\n" +
            "q\n" +
            "q\n" +
            "q\n" +
            "q\n" +
            "\n" +
            "txjoum\n" +
            "umkxjto\n" +
            "xjmtou\n" +
            "tuxmoj\n" +
            "xoujmt\n" +
            "\n" +
            "s\n" +
            "qcsdbt\n" +
            "zfvsyr\n" +
            "tes\n" +
            "sm\n" +
            "\n" +
            "rljihdcnaqutf\n" +
            "jaicdntbfhrqlou\n" +
            "fariqhutcnljd\n" +
            "frjchiaqplndutw\n" +
            "\n" +
            "xrnqaho\n" +
            "qonxhar\n" +
            "nxahqro\n" +
            "qrnhoax\n" +
            "\n" +
            "uk\n" +
            "ckg\n" +
            "\n" +
            "bxgqc\n" +
            "xbceq\n" +
            "qbcx\n" +
            "qbxc\n" +
            "\n" +
            "vqb\n" +
            "bejxq\n" +
            "\n" +
            "w\n" +
            "wydo\n" +
            "ucw\n" +
            "wu\n" +
            "\n" +
            "edtb\n" +
            "btdgeq\n" +
            "ebdt\n" +
            "detb\n" +
            "\n" +
            "ebm\n" +
            "ebm\n" +
            "meb\n" +
            "\n" +
            "uekbtqpzwhnvj\n" +
            "zewbpmqujrhxvdnkof\n" +
            "bqpjyhuevzknw\n" +
            "ntevbpujzhwqky\n" +
            "\n" +
            "vfldtsrqapgujinoz\n" +
            "utiqlgsjnda\n" +
            "qisgaudtlkjn\n" +
            "aqwsdujniltg\n" +
            "sundgilqtaj\n" +
            "\n" +
            "mxkdirtf\n" +
            "yfuokztxjgci\n" +
            "kqnfexariphbt\n" +
            "\n" +
            "s\n" +
            "s\n" +
            "s\n" +
            "s\n" +
            "s\n" +
            "\n" +
            "adg\n" +
            "dkwu\n" +
            "gdmk\n" +
            "qbdai\n" +
            "vorsdypn\n" +
            "\n" +
            "ulz\n" +
            "zlu\n" +
            "uzl\n" +
            "lzu\n" +
            "uzl\n" +
            "\n" +
            "eopktrshjvlzi\n" +
            "hdugpkjoia\n" +
            "oapkhij\n" +
            "biokjpmh\n" +
            "jokhip\n" +
            "\n" +
            "mf\n" +
            "f\n" +
            "fl\n" +
            "\n" +
            "yisk\n" +
            "kvcuz\n" +
            "wxtiqasko\n" +
            "\n" +
            "nec\n" +
            "cne\n" +
            "nec\n" +
            "\n" +
            "txzgpdojrbwkqefvh\n" +
            "bqwjdypxevozgfr\n" +
            "\n" +
            "fihxcgw\n" +
            "fixhwgc\n" +
            "gfchiwx\n" +
            "cfxgwih\n" +
            "\n" +
            "wigvpdnlkme\n" +
            "pixjcvyruheg\n" +
            "\n" +
            "jvlqsdyxf\n" +
            "xsqfjdyle\n" +
            "\n" +
            "bscgoeum\n" +
            "gom\n" +
            "qpornymgwxzdt\n" +
            "\n" +
            "gtnomjcfl\n" +
            "nptmfhrlbo\n" +
            "zexilfvdymquswktaon\n" +
            "\n" +
            "rwy\n" +
            "wrjtp\n" +
            "pjrx\n" +
            "zrag\n" +
            "\n" +
            "uamtwrbkoylfe\n" +
            "tmuheykwrfoa\n" +
            "uaroktyemfw\n" +
            "furemtwkyoa\n" +
            "\n" +
            "h\n" +
            "pdy\n" +
            "lqst\n" +
            "w\n" +
            "h\n" +
            "\n" +
            "gnycb\n" +
            "ycang\n" +
            "\n" +
            "hglvjfbkdoszupaq\n" +
            "vumel\n" +
            "cvnyxlu\n" +
            "wetlivnru\n" +
            "lecvu\n" +
            "\n" +
            "hnxyebuas\n" +
            "tgxbhiy\n" +
            "wqyxhmb\n" +
            "jflxwbyicvh\n" +
            "\n" +
            "vrxtjipzyqedl\n" +
            "aejplzdyqt\n" +
            "pljedtyqz\n" +
            "\n" +
            "maerbcw\n" +
            "snatizdkxv\n" +
            "frlwauhbm\n" +
            "\n" +
            "kuazhr\n" +
            "tahrzuk\n" +
            "uarkhz\n" +
            "\n" +
            "mznhw\n" +
            "wzamfhgr\n" +
            "uhvwgjzqm\n" +
            "eidbchpmklwsto\n" +
            "\n" +
            "qolj\n" +
            "ots\n" +
            "\n" +
            "m\n" +
            "j\n" +
            "s\n" +
            "\n" +
            "tydncfqwgmepx\n" +
            "ymfpdqxwecnt\n" +
            "nxecwpdfqtmy\n" +
            "cdnxqpfetwmy\n" +
            "\n" +
            "khaoxnuweymfqrl\n" +
            "uvfrjlxkwnhmeaoq\n" +
            "rotwfqcenlxhmaubk\n" +
            "mflhkanowxqeur\n" +
            "\n" +
            "mk\n" +
            "mlz\n" +
            "\n" +
            "kghnsx\n" +
            "xsnhgk\n" +
            "gxnshk\n" +
            "\n" +
            "grmfuzxapqtl\n" +
            "chyvmtzkulb\n" +
            "\n" +
            "s\n" +
            "s\n" +
            "s\n" +
            "s\n" +
            "\n" +
            "zcsa\n" +
            "z\n" +
            "zutkx\n" +
            "z\n" +
            "cz\n" +
            "\n" +
            "ntpv\n" +
            "rnjevq\n" +
            "lzsuhdkco\n" +
            "ge\n" +
            "\n" +
            "pktzy\n" +
            "zykq\n" +
            "zyk\n" +
            "yzk\n" +
            "ykqz\n" +
            "\n" +
            "qnre\n" +
            "rdgnaswj\n" +
            "qrn\n" +
            "\n" +
            "gylpqcro\n" +
            "byqehivlzuro\n" +
            "wrcqsoyndlf\n" +
            "orwpylmq\n" +
            "\n" +
            "jbkwvgotfinhm\n" +
            "otkfjviwnbhg\n" +
            "gsobfhykivwjn\n" +
            "oiwnmfghbvkj\n" +
            "\n" +
            "tlnmpbaoq\n" +
            "mviklan\n" +
            "ianml\n" +
            "lmajn\n" +
            "lkamn\n" +
            "\n" +
            "skmgdvqrchelzf\n" +
            "vhrszlkfcmgedq\n" +
            "\n" +
            "faxnsmzvirlkh\n" +
            "eahmlnrusxizf\n" +
            "qsxiglphmznarf\n" +
            "\n" +
            "gzmcbsh\n" +
            "gcshmbz\n" +
            "zmbhscg\n" +
            "zshmcgb\n" +
            "zfmsbvhgc\n" +
            "\n" +
            "qfalhdgcsn\n" +
            "nqgdhfcasl\n" +
            "gqhalsndcf\n" +
            "ncghdsaqfl\n" +
            "ngcsfldqah\n" +
            "\n" +
            "teqr\n" +
            "rqezt\n" +
            "qtre\n" +
            "etrq\n" +
            "qrte\n" +
            "\n" +
            "kcyhbfxi\n" +
            "ckixthb\n" +
            "kpbhixtc\n" +
            "\n" +
            "ge\n" +
            "eg\n" +
            "ge\n" +
            "dyeg\n" +
            "eg\n" +
            "\n" +
            "cwmo\n" +
            "cmwo\n" +
            "mowc\n" +
            "cowm\n" +
            "omwc\n" +
            "\n" +
            "e\n" +
            "b\n" +
            "b\n" +
            "\n" +
            "jvmzniyusgc\n" +
            "vdukmepyczl\n" +
            "mzucvby\n" +
            "ukvyzcm\n" +
            "dckuxzvmy\n" +
            "\n" +
            "lto\n" +
            "ltnbke\n" +
            "ylugto\n" +
            "luzt\n" +
            "ltv\n" +
            "\n" +
            "savfmzhpyid\n" +
            "aszvmhpdfy\n" +
            "ybapjsxmdvfnzh\n" +
            "\n" +
            "tpjvwlqiko\n" +
            "hpqvcoamtbd\n" +
            "\n" +
            "qiesufrhb\n" +
            "iqbzrhsuef\n" +
            "usbieqhfrg\n" +
            "hebiuqsfr\n" +
            "\n" +
            "achgivjylqtsen\n" +
            "ijlnetryhgc\n" +
            "\n" +
            "equgysxn\n" +
            "hadozb\n" +
            "\n" +
            "ubdfvrkseaijlyonmtzcx\n" +
            "okbdmerusycjvfitlxanz\n" +
            "rijnyzlxafvudmcksebto\n" +
            "wsujvnkmoayclqfzbetxidr\n" +
            "\n" +
            "remvgdwalqyhcjpzo\n" +
            "ejaczhvpgwlyrqdo\n" +
            "gqpwchryejaozdlv\n" +
            "ovgdzqpywjhlrcxae\n" +
            "wojhlyevgcpaqrzd\n" +
            "\n" +
            "hasivzcfepyxbrwqj\n" +
            "btypvgxwecnmzlaqi\n" +
            "\n" +
            "buvxhewzd\n" +
            "frhmdxbesu\n" +
            "\n" +
            "sadcyb\n" +
            "dbys\n" +
            "shdrvbf\n" +
            "\n" +
            "qaf\n" +
            "fqa\n" +
            "aqjf\n" +
            "qagfw\n" +
            "\n" +
            "yw\n" +
            "yw\n" +
            "pyw\n" +
            "yw\n" +
            "yw\n" +
            "\n" +
            "omwpxa\n" +
            "wapoxm\n" +
            "mxoapfbw\n" +
            "mpaoxw\n" +
            "wpmxoa\n" +
            "\n" +
            "hsnypozurjbt\n" +
            "kmcnbuyrposhj\n" +
            "\n" +
            "lvwjezmsac\n" +
            "wezlmajys\n" +
            "lmaeszjw\n" +
            "\n" +
            "kxtwmrc\n" +
            "jkfytbcwq\n" +
            "\n" +
            "orxdwh\n" +
            "wxetro\n" +
            "txrowp\n" +
            "efrxwo\n" +
            "\n" +
            "adxtgurfel\n" +
            "hmvczxaokqsj\n" +
            "\n" +
            "bytcwakhujns\n" +
            "leuthfgq\n" +
            "hiodgmvtu\n" +
            "tulrxphfz\n" +
            "\n" +
            "ujbonmlqhwaprvcsitegdfkx\n" +
            "fvcdnozjkbugxatwshmriqepl\n" +
            "xisvpekqawnrlgocdftuhbjm\n" +
            "ulpqsjcgwhkbrftvenoidamx\n" +
            "\n" +
            "azj\n" +
            "zadj\n" +
            "jaz\n" +
            "jza\n" +
            "\n" +
            "lrqaouvdmizsybtcxj\n" +
            "mvhuxrsoyjli\n" +
            "\n" +
            "daxg\n" +
            "ayudzkbge\n" +
            "dcgfhanlp\n" +
            "dqcsghwar\n" +
            "\n" +
            "vacreqdl\n" +
            "alcedqr\n" +
            "lcaodqer\n" +
            "lecdarq\n" +
            "\n" +
            "mxkzonlajhisegvrbpctyu\n" +
            "aigbxvdmekolptshzn\n" +
            "zpxmglvkbitoashne\n" +
            "\n" +
            "gmxolsvyure\n" +
            "xjepmlgizsfbcqho\n" +
            "\n" +
            "uhjvgfxrwmbolk\n" +
            "csityednaz\n" +
            "\n" +
            "jzig\n" +
            "zpigjv\n" +
            "\n" +
            "weixfdptkcz\n" +
            "fydcwxerzmkipt\n" +
            "cfdekwzxipvt\n" +
            "fzpwxteikdc\n" +
            "\n" +
            "vsewfkyl\n" +
            "chtxidjprobn\n" +
            "xaqgp\n" +
            "rmtaqhz\n" +
            "\n" +
            "vxkwjodpscmtlguaq\n" +
            "msugwvqpxeljyo\n" +
            "gifjbmpwuvoshlyzqx\n" +
            "\n" +
            "vcgmuisfjnehdozxtp\n" +
            "muxsdnoiefcjhptvg\n" +
            "txuojwhpimdcfvgsen\n" +
            "oltnmsbfagvphiejkyuxdcr\n" +
            "\n" +
            "mcdpv\n" +
            "dcmz\n" +
            "nfmdjcwsa\n" +
            "\n" +
            "rcnyoxmqztghljpe\n" +
            "znebjrgxlyqvcshtm\n" +
            "ulcryhxzqntjmeg\n" +
            "morhwzjqcyxglten\n" +
            "rfzxhjniqytgceml\n" +
            "\n" +
            "zavrpdbugqjk\n" +
            "cudkqrvpfyswm\n" +
            "qkupvdrtoi\n" +
            "uqvkldpxr\n" +
            "\n" +
            "knoex\n" +
            "exnk\n" +
            "neklx\n" +
            "\n" +
            "ywvntofgpjm\n" +
            "thwmnj\n" +
            "tmnshejxw\n" +
            "minabwxtj\n" +
            "\n" +
            "nkdwr\n" +
            "ndruk\n" +
            "ndkr\n" +
            "rdkn\n" +
            "rnkdu\n" +
            "\n" +
            "tixalqjdrvmoh\n" +
            "rigohvmjldqtxa\n" +
            "jqtvhmxdaliro\n" +
            "jimxdrqvohlta\n" +
            "bvlraqhdxjiotm\n" +
            "\n" +
            "nsvazbjxkipo\n" +
            "vnzcohpfmsjigtkab\n" +
            "siobvzkpjan\n" +
            "oszbkepuvanij\n" +
            "\n" +
            "nux\n" +
            "xn\n" +
            "nx\n" +
            "nxv\n" +
            "\n" +
            "xenrcvihm\n" +
            "ziykhodmq\n" +
            "igbmfwexhuj\n" +
            "\n" +
            "ktbghvudixa\n" +
            "vhgbcxruia\n" +
            "aguxbvhicr\n" +
            "\n" +
            "lse\n" +
            "eljvs\n" +
            "sel\n" +
            "\n" +
            "ehrygnzaxf\n" +
            "zlskujqycx\n" +
            "\n" +
            "glof\n" +
            "bim\n" +
            "t\n" +
            "um\n" +
            "\n" +
            "zgaehwxytro\n" +
            "xwgeyzcrht\n" +
            "ryexgwthza\n" +
            "rwxgyebzth\n" +
            "wyrzxhtaeg\n" +
            "\n" +
            "nqejopzctdugmriwh\n" +
            "pwhtoumjrdgkezcaqn\n" +
            "odwymunjqepchztg\n" +
            "xjduamnhzoqecptwg\n" +
            "\n" +
            "ejihvqaycznfdbtrpgumko\n" +
            "vtrjibznghamkwyqeduflop\n" +
            "osdmeiqranfbgythkzxvcjpu\n" +
            "\n" +
            "nkaxqydlsmvz\n" +
            "vbjyi\n" +
            "bityv\n" +
            "rtpbvyo\n" +
            "\n" +
            "qsfnjdhcobtzg\n" +
            "sedqjgoznwtkb\n" +
            "zdubspqojgnt\n" +
            "bwgntzjosqedl\n" +
            "\n" +
            "gkoqsirndwvyuzthamfjblc\n" +
            "haqsvbcyumnfpgtdokjlrwzi\n" +
            "idvyqehnamfwoxutzkgsjrcbl\n" +
            "scjlmugtwhdnazbqkroiyvf\n" +
            "qrozykbhugviptwamnlfsdcj\n" +
            "\n" +
            "kbzpdujqvtxesnhgr\n" +
            "wsnqjhbrdgxkvueptz\n" +
            "gdbukvtznpehqxjrs\n" +
            "rpxsehnjtgfukvzbqd\n" +
            "jdrkzhegbnxasvitupq\n" +
            "\n" +
            "wozpasi\n" +
            "aoizsgpw\n" +
            "aojzisw\n" +
            "zosaiw\n" +
            "ioaswz\n" +
            "\n" +
            "ashtecdbifwyzroqgkl\n" +
            "ozyrsefqhwbkcagltdi\n" +
            "qzocylgriwfhtbkase\n" +
            "oagfczsekiqbwthrly\n" +
            "vysribwkuagfolctqzhe\n" +
            "\n" +
            "sgbvexlhokctn\n" +
            "cktljevhubp\n" +
            "iebtdxlakgcvhmzy\n" +
            "\n" +
            "ropsxbqdyhzuntmekj\n" +
            "hgrneqzkmdotuypxb\n" +
            "ukxztpqwyrimdnohbe\n" +
            "ctvrzonqpybxmekludh\n" +
            "uthrpyodmwzxfeqkbn\n" +
            "\n" +
            "eqig\n" +
            "bad\n" +
            "\n" +
            "swaephtuvizdbqg\n" +
            "dewstalgqipvubz\n" +
            "zepbtmiguadsqwv\n" +
            "pmqdgwtayevbszui\n" +
            "apeuzysivbqtgdw\n" +
            "\n" +
            "dstkjxubpfv\n" +
            "zdntjkfrbypuihq\n" +
            "okubftpdzjmiwhq\n" +
            "\n" +
            "epbfzaygk\n" +
            "mpkz\n" +
            "kwszpi\n" +
            "\n" +
            "wbhvifor\n" +
            "bvrhfwk\n" +
            "rhbwfv\n" +
            "\n" +
            "ibtlvzkdpwgcu\n" +
            "zkvdaitqbfwgcu\n" +
            "\n" +
            "mujwybpkqlv\n" +
            "cgqjnlhtsaxiwrmkyv\n" +
            "\n" +
            "cf\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "\n" +
            "irch\n" +
            "tfrzxku\n" +
            "\n" +
            "c\n" +
            "c\n" +
            "\n" +
            "zfeyrtlha\n" +
            "om\n" +
            "\n" +
            "e\n" +
            "h\n" +
            "oh\n" +
            "pu\n" +
            "\n" +
            "xtqypjhm\n" +
            "hmxypqjt\n" +
            "pztjmysxhd\n" +
            "xmhpoyjt\n" +
            "tomjphyx\n" +
            "\n" +
            "nohjcgzxiswbmetrdyqvpalkfu\n" +
            "htgqvwsojniyrkxcmpbzlefuad\n" +
            "\n" +
            "pu\n" +
            "up\n" +
            "pu\n" +
            "up\n" +
            "\n" +
            "vdahlxznij\n" +
            "xakidhnl\n" +
            "\n" +
            "xdyuikfgc\n" +
            "gyczqafpd\n" +
            "temcylgsd\n" +
            "\n" +
            "nrfme\n" +
            "mnfrel\n" +
            "\n" +
            "ifhpcr\n" +
            "cbhri\n" +
            "hcir\n" +
            "chir\n" +
            "crbhi\n" +
            "\n" +
            "nfxemqah\n" +
            "xfunrhem\n" +
            "\n" +
            "dgstmwf\n" +
            "fdkmsl\n" +
            "\n" +
            "sjvrfqdxklyzucbgwmehiap\n" +
            "jlugpkiqhosrnbzevfmaycwd\n" +
            "\n" +
            "fczn\n" +
            "zcnf\n" +
            "\n" +
            "efsntzoldb\n" +
            "holnrbfesztu\n" +
            "zesoltfbn\n" +
            "ceonfzlsbt\n" +
            "blfkpozntse\n" +
            "\n" +
            "ecuhijwsrdgptafqv\n" +
            "rnxcbvpkqzouiyl\n" +
            "\n" +
            "vnkzqhedbaljx\n" +
            "ixenzovyla\n" +
            "lawczgvxntdfmue\n" +
            "jzaepnlvx\n" +
            "\n" +
            "ewdcailnjhgrvx\n" +
            "dhjeragncxiylwv\n" +
            "hjxewdcgaivnlr\n" +
            "\n" +
            "pw\n" +
            "w\n" +
            "w\n" +
            "\n" +
            "em\n" +
            "q\n" +
            "\n" +
            "sqbu\n" +
            "ipugz\n" +
            "cekbumy\n" +
            "\n" +
            "r\n" +
            "r\n" +
            "jc\n" +
            "e\n" +
            "\n" +
            "mh\n" +
            "hm\n" +
            "hm\n" +
            "mh\n" +
            "mh\n" +
            "\n" +
            "cfpgkrnwmliohqzt\n" +
            "ifwhrktopnqgcml\n" +
            "rmogfcliqwkthnp\n" +
            "ickhqpwrtmfngol\n" +
            "nflkwqcphriogmt\n" +
            "\n" +
            "ktglnawhydqbcrvizmf\n" +
            "kfhigbancduezmrlvy\n" +
            "hgdbfvyikacrlnzm\n" +
            "kmgczvnahriyfdljb\n" +
            "\n" +
            "pagvqydfmecxjbzswhn\n" +
            "rzohnqtdckmsup\n" +
            "\n" +
            "oc\n" +
            "oc\n" +
            "co\n" +
            "oc\n" +
            "oc\n" +
            "\n" +
            "umjkfeytvzpsb\n" +
            "spuyeztvfk\n" +
            "kfzetypvus\n" +
            "fustzkvpye\n" +
            "retuikyflvnazcsp\n" +
            "\n" +
            "nfqz\n" +
            "nzfq\n" +
            "qzfn\n" +
            "qnzf\n" +
            "\n" +
            "i\n" +
            "i\n" +
            "s\n" +
            "i\n" +
            "\n" +
            "tchebzypafxgdirlmj\n" +
            "bzupasgntxqfdirje\n" +
            "\n" +
            "xpzrmeisqnbdhjl\n" +
            "qhjdmseilprbnz\n" +
            "nqlsipkjmhrzebd\n" +
            "yrjlwmensbapivqhzgd\n" +
            "hdrzqnsomjbplie\n" +
            "\n" +
            "lfwd\n" +
            "cmfvrlwp\n" +
            "klfw\n" +
            "fwl\n" +
            "dqfwlbhg\n" +
            "\n" +
            "v\n" +
            "d\n" +
            "q\n" +
            "fw\n" +
            "\n" +
            "gbuzrneplha\n" +
            "euzprnqadlgh\n" +
            "ealguphznrf\n" +
            "nhabzlxrcgpue\n" +
            "\n" +
            "vfpnqghusmkde\n" +
            "ldotwpsy\n" +
            "\n" +
            "fwpvbymnzgdjro\n" +
            "whjepnofbdymvzr\n" +
            "\n" +
            "mlg\n" +
            "lmg\n" +
            "fmgl\n" +
            "gml\n" +
            "glm\n" +
            "\n" +
            "cug\n" +
            "dj\n" +
            "s\n" +
            "\n" +
            "jv\n" +
            "tvi\n" +
            "eijda\n" +
            "hlkpnrsum\n" +
            "\n" +
            "jawgleqs\n" +
            "cduziypmhrxfonl\n" +
            "\n" +
            "edmuictzolbqvnk\n" +
            "vlkzngqtiuaebpcwdm\n" +
            "ivjumdnlqtkcezb\n" +
            "kemvtisdqbcuznrl\n" +
            "\n" +
            "enqpkozxbmfrj\n" +
            "bwnqmpzkhejfg\n" +
            "foqpunmyckzjxbte\n" +
            "fjypekqbmzn\n" +
            "qdvpinbamskzfjle\n" +
            "\n" +
            "t\n" +
            "t\n" +
            "c\n" +
            "t\n" +
            "t\n" +
            "\n" +
            "fspwjzylebimvkdtrcung\n" +
            "zvnodtbprjfcywsexkiul\n" +
            "wjslpekbizadtuyvcfhrnq\n" +
            "\n" +
            "zuocidaysqh\n" +
            "puagdlnwrqscoiy\n" +
            "\n" +
            "zstfuhbocpi\n" +
            "btmcupshozf\n" +
            "zcesufhoptbrm\n" +
            "\n" +
            "yjzmq\n" +
            "omwj\n" +
            "\n" +
            "bmxdychwi\n" +
            "yxdriwc\n" +
            "\n" +
            "yzs\n" +
            "yzs\n" +
            "zyatsq\n" +
            "yszc\n" +
            "\n" +
            "ujmefqzrds\n" +
            "jusmfreqzd\n" +
            "edufrszjmq\n" +
            "esjzmqufdr\n" +
            "jfdziruqmtes\n" +
            "\n" +
            "mdryvueb\n" +
            "rbyvemud\n" +
            "bhdyexvumr\n" +
            "udevyrbm\n" +
            "reduymvb\n" +
            "\n" +
            "rolwbjs\n" +
            "rlnwosb\n" +
            "\n" +
            "togdqxs\n" +
            "sxdqbtmug\n" +
            "pfgaqsdiety\n" +
            "\n" +
            "lrfophzwysukgxm\n" +
            "knhuszxfcgvdmobwp\n" +
            "\n" +
            "eb\n" +
            "e\n" +
            "e\n" +
            "epz\n" +
            "\n" +
            "lxstfqrgd\n" +
            "xdlqfrgst\n" +
            "tfxgrdqsl\n" +
            "stgxdrflq\n" +
            "\n" +
            "vyqli\n" +
            "fz\n" +
            "jkf\n" +
            "\n" +
            "hg\n" +
            "h\n" +
            "h\n" +
            "h\n" +
            "h\n" +
            "\n" +
            "fojxgyqhbdts\n" +
            "ogjbhqtfsyx\n" +
            "foqxgbushyj\n" +
            "htbqjofyxgs\n" +
            "\n" +
            "nzhrvtspfomyaxkuqceil\n" +
            "zygjmnixvscdbuqa\n" +
            "\n" +
            "d\n" +
            "g\n" +
            "\n" +
            "nhxcvump\n" +
            "edzcwfsqorkb\n" +
            "\n" +
            "evhncroiwxgk\n" +
            "cwonkxrisehv\n" +
            "rihwcgkvnxeo\n" +
            "vnehicwkxor\n" +
            "\n" +
            "wfvynd\n" +
            "ywfmvdn\n" +
            "wfdvny\n" +
            "\n" +
            "gnyvafikxolcprwzqs\n" +
            "aisnceyjqktofgrxzw\n" +
            "\n" +
            "pznetaolmxgwvhsdqkrbyc\n" +
            "ybalreuhsnmfgkvzwpdcx\n" +
            "hzwmvgnpsbeckayxdlrf\n" +
            "epbhnkdxcjzwsagvrmuyl\n" +
            "drawvnebzsykgjhclmxp\n" +
            "\n" +
            "ezy\n" +
            "zye\n" +
            "yez\n" +
            "\n" +
            "wgdxsvhafpcjko\n" +
            "vxjpfkghdsolca\n" +
            "cohsbgpkjadvfx\n" +
            "hyvogcxdkjafps\n" +
            "avkfdcjpogxhs\n" +
            "\n" +
            "eomalpgqsjnf\n" +
            "omqpvlejna\n" +
            "dvelmpquojan\n" +
            "\n" +
            "wfmvjonsz\n" +
            "dlzfhnpsgwvcm\n" +
            "msnezwfv\n" +
            "vjbfnmswze\n" +
            "zfsvqmnjw\n" +
            "\n" +
            "kypraeoszfbv\n" +
            "xiwfbtkhzvyqrno\n" +
            "mzdfkcvbrywo\n" +
            "\n" +
            "cgibxfytavo\n" +
            "exyvnumapstzghkldw\n" +
            "vtbgqxjyfra\n" +
            "\n" +
            "kywqtenrs\n" +
            "ryqnesktw\n" +
            "sntewrbkyq\n" +
            "qnyrwkets\n" +
            "ksrytneqw\n" +
            "\n" +
            "bwx\n" +
            "bxw\n" +
            "bxw\n" +
            "wbx\n" +
            "dwbx\n" +
            "\n" +
            "dzfhuysotiljk\n" +
            "rzyipfxkqjltdbsn\n" +
            "ysctgzeijfaldvk\n" +
            "\n" +
            "gchblktyvamensjzrxdpoifw\n" +
            "jikpvlydfourtmcabxzwghe\n" +
            "clitbevyxrwkfgmajzphdo\n" +
            "\n" +
            "rfjxt\n" +
            "rjtfx\n" +
            "xhtprjf\n" +
            "txfrgj\n" +
            "ntfjrx\n" +
            "\n" +
            "buf\n" +
            "ugbf\n" +
            "ftu\n" +
            "\n" +
            "wmly\n" +
            "wylmi\n" +
            "lwym\n" +
            "\n" +
            "yihgtzf\n" +
            "tfszyg\n" +
            "\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "\n" +
            "jt\n" +
            "p\n" +
            "os\n" +
            "kirnmeavhd\n" +
            "\n" +
            "vceby\n" +
            "vyebpc\n" +
            "bcepyv\n" +
            "beicvy\n" +
            "bcyevp\n" +
            "\n" +
            "noxurmlfzqejahctpbygs\n" +
            "uhzrlfaqtgjecmpoxbysn\n" +
            "\n" +
            "maki\n" +
            "ik\n" +
            "ixk\n" +
            "kei\n" +
            "\n" +
            "loadfkj\n" +
            "ucforvjdgh\n" +
            "dmjtnipxsb\n" +
            "\n" +
            "xedyq\n" +
            "yeqxd\n" +
            "yeqxd\n" +
            "\n" +
            "ptkuhyvnegowrjxmlba\n" +
            "wmoreltvphkaujybxn\n" +
            "reqbvnlmtoxwphyjuzka\n" +
            "\n" +
            "qgef\n" +
            "egq\n" +
            "heqgwsuz\n" +
            "geq\n" +
            "\n" +
            "bkdyhs\n" +
            "ytexipko\n" +
            "kydfhqjl\n" +
            "wklhyf\n" +
            "\n" +
            "fprgenljakhovbxsyziuqtdmwc\n" +
            "ckrvfhtwqslypbzdgneiuxamj\n" +
            "tiyzmgqdscelhujvxkrawpfbn\n" +
            "\n" +
            "sbcxi\n" +
            "csxib\n" +
            "xscqbi\n" +
            "\n" +
            "fcejtsavprn\n" +
            "tnfacejvpusr\n" +
            "qoscznfjlyxtampredv\n" +
            "vfejscptarn\n" +
            "\n" +
            "bwe\n" +
            "bew\n" +
            "bew\n" +
            "web\n" +
            "bew\n" +
            "\n" +
            "drikb\n" +
            "nkbriqd\n" +
            "dzikrb\n" +
            "kdbir\n" +
            "bdvlirk\n" +
            "\n" +
            "ozmw\n" +
            "wuzr\n" +
            "ausw\n" +
            "tywci\n" +
            "\n" +
            "czjyoptfnsvmqurekwix\n" +
            "refjtpmqvckonyxzwuis\n" +
            "qpixwtnfjrcymvoseuzk\n" +
            "vkwotrmcneujfpzsixyq\n" +
            "jqfopnetwcvukxzsyrmi\n" +
            "\n" +
            "vaweukirgx\n" +
            "uagkirwefvx\n" +
            "wikyexdpgztsvoar\n" +
            "rvwxeajckimg\n" +
            "irwgxkheav\n" +
            "\n" +
            "wkazrq\n" +
            "r\n" +
            "myr\n" +
            "r\n" +
            "hrv\n" +
            "\n" +
            "iufbyeqtxnvprkcm\n" +
            "ryfmjtdzqxulhkgewo\n" +
            "\n" +
            "kwzvfeocqdlytn\n" +
            "dznhcloqye\n" +
            "lcegqzybndujo\n" +
            "\n" +
            "vxlopgns\n" +
            "mtk\n" +
            "\n" +
            "tkdcaxf\n" +
            "tgkdcf\n" +
            "fcked\n" +
            "kdorspcf\n" +
            "\n" +
            "hp\n" +
            "rhazky\n" +
            "qhpx\n" +
            "\n" +
            "unysbohr\n" +
            "pukogixhmyfqb\n" +
            "\n" +
            "mhpwz\n" +
            "zwmp\n" +
            "\n" +
            "xulrhwvn\n" +
            "wrvghn\n" +
            "nhciwjorv\n" +
            "nwrhgv\n" +
            "\n" +
            "jdkbotqayzv\n" +
            "lrkesigodpjvuqw\n" +
            "rqksolvfmidjuc\n" +
            "\n" +
            "zvpbtxmnaelkfco\n" +
            "oavfnlmpetzxbk\n" +
            "lnfzkxeoamtbpv\n" +
            "\n" +
            "r\n" +
            "nb\n" +
            "n\n" +
            "f\n" +
            "aok\n" +
            "\n" +
            "emkwvbdfj\n" +
            "fjkbnveo\n" +
            "jkvobe\n" +
            "kqehbwvj\n" +
            "lebkvjgcxt\n" +
            "\n" +
            "wsalguinytzrc\n" +
            "aucqgms\n" +
            "dacusg\n" +
            "uhefcgas\n" +
            "\n" +
            "bhrxjvpcqwfzan\n" +
            "bgaxorivnszqh\n" +
            "ruamglqxhtsnvzb\n" +
            "bvhrxzqnya\n" +
            "\n" +
            "raeskxt\n" +
            "aestk\n" +
            "kstgae\n" +
            "setka\n" +
            "atsek\n" +
            "\n" +
            "fipmtwojskaqyxnvdche\n" +
            "hxzcibuolysjr\n" +
            "\n" +
            "keguid\n" +
            "ugmkewi\n" +
            "xgerkhipu\n" +
            "\n" +
            "ytmxvfruoabcqejidkzsgph\n" +
            "bokqdimgatzpcerjsyfvxu\n" +
            "yszvmdptexbiqcjrouagkf\n" +
            "fvoyekijqsxtazbudgcmpr\n" +
            "xamcgftivdejzqrbpokuys\n" +
            "\n" +
            "uqadcpibf\n" +
            "bcqupa\n" +
            "luabcqprk\n" +
            "apucbqm\n" +
            "uocsqabp\n" +
            "\n" +
            "cyhlfeqoupbdmwvzni\n" +
            "qwimvjuzepanflbcd\n" +
            "\n" +
            "mex\n" +
            "a\n" +
            "i\n" +
            "\n" +
            "odajq\n" +
            "qxovi\n" +
            "vlhoq\n" +
            "\n" +
            "nmiw\n" +
            "wi\n" +
            "oiw\n" +
            "woyi\n" +
            "\n" +
            "wxzfidlqmptsvnygeoauchj\n" +
            "pvyxgncdewizlstojqhmua\n" +
            "mtinhuavzljgpqyskoewcxd\n" +
            "qsphxrjgmuyaiwcznlvdteo\n" +
            "\n" +
            "heqcjz\n" +
            "qeczhj\n" +
            "hejcqz\n" +
            "jhzqec\n" +
            "ezhqjwc\n" +
            "\n" +
            "vjqt\n" +
            "tqj\n" +
            "tjq\n" +
            "tqj\n" +
            "\n" +
            "prqfadzewtu\n" +
            "zrwadyu\n" +
            "\n" +
            "lk\n" +
            "kl\n" +
            "kl\n" +
            "\n" +
            "guxtnkzjalim\n" +
            "lzaxmikgjtnv\n" +
            "mgajdnlpfkxiqht\n" +
            "\n" +
            "zwi\n" +
            "i\n" +
            "\n" +
            "eygsiomnwdf\n" +
            "untsygjf\n" +
            "\n" +
            "vq\n" +
            "v\n" +
            "tv\n" +
            "\n" +
            "ngoqhlwje\n" +
            "jchldgqnpe\n" +
            "qjngrsizleh\n" +
            "\n" +
            "bwlkyfdp\n" +
            "gbmflwhp\n" +
            "\n" +
            "coiy\n" +
            "il\n" +
            "i\n" +
            "i\n" +
            "\n" +
            "rmgloqzsfyvdjnexac\n" +
            "aopdyvqgsmclrxetfjn\n" +
            "lxnyasqodrgvmcfje\n" +
            "\n" +
            "zigobnu\n" +
            "znkrbgpoiu\n" +
            "hbovinzugw\n" +
            "ginozubj\n" +
            "\n" +
            "ljyrhtkpsnwcfbmax\n" +
            "bdljpxaikhrcgzeutywqvs\n" +
            "\n" +
            "x\n" +
            "ak\n" +
            "gds\n" +
            "\n" +
            "ytusv\n" +
            "syvut\n" +
            "ysutv\n" +
            "yoxgvuds\n" +
            "syuv\n" +
            "\n" +
            "lixawndvumgojez\n" +
            "hmrpwfzdncyvbsqki\n" +
            "\n" +
            "onqjv\n" +
            "vloxkhnj\n" +
            "ovnjd\n" +
            "ojnv\n" +
            "vojdin\n" +
            "\n" +
            "rjepfiwskovacybhgnzx\n" +
            "dlekbnocyutvahrmzsjxwg\n" +
            "kgyqnwaehfxvprjzscob\n" +
            "\n" +
            "vbrdic\n" +
            "ufwyqex\n" +
            "\n" +
            "vedln\n" +
            "ven\n" +
            "\n" +
            "msckyitxdjvauqofhrnl\n" +
            "dauptjysmhfxngzcvirboqkl\n" +
            "qlnumovjkwfdxhaiycsrte\n" +
            "\n" +
            "w\n" +
            "xw\n" +
            "\n" +
            "rxfdlwchmybezpqgntus\n" +
            "yqmpibrahtoxuc\n" +
            "yubxhcpqkitmr\n" +
            "\n" +
            "xwpdj\n" +
            "cwjpxd\n" +
            "pdwxj\n" +
            "yjxpdw\n" +
            "\n" +
            "avdxkzpobusrtymgih\n" +
            "fwnelcq\n" +
            "ncjfq\n" +
            "\n" +
            "rzhbvoplisfgdknujacxq\n" +
            "pcbuifnsdgqaxlhvjo\n" +
            "gjbcpfnhovusxlatdqim\n" +
            "\n" +
            "nvrozpjuaxhwdkes\n" +
            "wafvhsrokendxju\n" +
            "\n" +
            "zdqbxmgnpcfivr\n" +
            "vyprdqszfubcw\n" +
            "cbarfuywqpdvzhsl\n" +
            "\n" +
            "z\n" +
            "z\n" +
            "z\n" +
            "zoj\n" +
            "z\n" +
            "\n" +
            "rglswbymhpao\n" +
            "abmgyslhwop\n" +
            "syglhmaopwb\n" +
            "\n" +
            "bvaiwtlgqykcsmnjdzo\n" +
            "ytosacmfnhwl\n" +
            "antyleomuscpw\n" +
            "afylcnostmwp\n" +
            "\n" +
            "mtgjr\n" +
            "gnlwt\n" +
            "tfhdouqpisyg\n" +
            "tlgew\n" +
            "gmvt\n" +
            "\n" +
            "tungmazdvsrwhoceqpkj\n" +
            "fzkrhyjcsueowadmxtnp\n" +
            "jhrkwoescaldmtpzuxny\n" +
            "\n" +
            "gctqxhvku\n" +
            "cqtxglhsvu\n" +
            "zuvgtbhcxwqr\n" +
            "jcquhtxgsv\n" +
            "uvqhytkcxg\n" +
            "\n" +
            "duqaiktehfxb\n" +
            "extbizfudpa\n" +
            "tasjedcvwmgxrbfliu\n" +
            "inahpdxteubf\n" +
            "\n" +
            "xmqga\n" +
            "doain\n" +
            "cazfrh\n" +
            "wptusa\n" +
            "jpa\n" +
            "\n" +
            "okztgcxwfnbpuv\n" +
            "akqyzviohlfrdmbtpjsn\n" +
            "\n" +
            "gq\n" +
            "jgqs\n" +
            "gq\n" +
            "qg\n" +
            "\n" +
            "fxkws\n" +
            "btxfw\n" +
            "xewfs\n" +
            "ofxw";
}
